### ISSUE TITLE
YACL contains dependencies from uncommon repos

### ISSUE THREAD

**Issue by Qendolin** [isXander/YetAnotherConfigLib#111]
Between yacl 3.0.0 and 3.2.0 your dependency structure changed so that a simple
```groovy
modImplementation "dev.isxander.yacl:yet-another-config-lib-fabric:3.2.0+1.20"
```
doesn't work. 
Gradle fails to resolve your transitive dependencies since they are hosted on unknown repositories.

- `com.twelvemonkeys.imageio` requires `https://oss.sonatype.org/content/repositories/snapshots`
- `org.quiltmc.parsers` requires `https://maven.quiltmc.org/repository/release`

**Comment by xanthian** [comment]
same for 3.2.1

**Comment by isXander** [comment]
It is true that you need these repositories for YACL to work. The next version the ImageIO lib is back on maven central, but until I start mirroring quilt parsers I'll just need to reflect this in the documentation.

**Comment by isXander** [comment]
I know mirror quilt parsers!
