### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Its-a-Club** [isXander/YetAnotherConfigLib#115]
Hi I don't know much on how to read crash reports but I seen your dev name at the top,  was wondering if you could possibly assist me
this is the only mod I have installed from you. Any info would be greatly appreciated. 
[crash-2023-10-02_19.18.08-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/12822574/crash-2023-10-02_19.18.08-client.txt)

**Comment by JackFred2** [comment]
You have a version of YACL for an older version of Minecraft; [get the version for 1.20.2](https://modrinth.com/mod/yacl/version/3.2.1+1.20.2-fabric).
