### ISSUE TITLE
[Enhancement] reference fabric api directly not the fapi resource loader module

### ISSUE THREAD

**Issue by Linguardium** [isXander/YetAnotherConfigLib#127]
https://github.com/isXander/YetAnotherConfigLib/blob/953645023c829735663493511390948bf69714f8/fabric/src/main/resources/fabric.mod.json#L22C9-L22C9

By referencing this, if someone doesnt include fapi in their mod list they get a popup with an obscure mod id that is not readily readable by players. better to depend on the fabric api as a whole (at least for the CF/MR published versions of the mod that players would download)

**Comment by isXander** [comment]
I depend on only this mod so you don't actually need Fabric API at all, because afaik Sodium actually includes this fabric API module. 

It's not my fault that Fabric Loader's error guis are so horrificly bad.

**Comment by Linguardium** [comment]
using "Sodium actually includes this fabric API module." as a reason why you shouldnt resolve it seems questionable.  any other mod may include a module, sure, but if you dont then it doesnt matter... 

Alternatively, then, add the module as an include?
