### ISSUE TITLE
Crash in minecraft 1.20.4

### ISSUE THREAD

**Issue by Menion2k** [isXander/YetAnotherConfigLib#158]
This is referenced to a feedback from fabric discussion board: https://github.com/orgs/FabricMC/discussions/3639

Hi all

I am trying to launch via multiMC a farly basic MC 1.20.4 Java Edition. I bring into the mods YetAnotherConfigLib (3.3.2) with Fabric Resource Loader V0 0.11.9 and Fabric APUI 0.96.4 required for Controlify.

But MC crashes at startup (yes I launched once online). The mod that causes the crash is Fabric Resource loader v0 (tried also older version), its pressence is enought to kick the crash.

It complains of:

java.lang.AbstractMethodError: Receiver class net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator$$Lambda/0x000001d881b14f60 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_3262 method_52424(java.lang.String)' of interface net.minecraft.class_3288$class_7680.

In another instance I got instead:
java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_30613(java.io.File)'

Attachments can be downloaded from the referenced issue on FabricMC

**Comment by isXander** [comment]
Not to do with YACL. Make sure fabric api is up to date.
