### ISSUE TITLE
Collapsible section arrows should be permanently visible

### ISSUE THREAD

**Issue by Madis0** [isXander/YetAnotherConfigLib#16]
...otherwise they only serve as labels because there is no indication people should hover them.

**Comment by isXander** [comment]
What I don't want is the option list to feel to crowded, maybe the button arrow is always visible and on hover of the group entry the button texture becomes visible?

**Comment by Madis0** [comment]
> What I don't want is the option list to feel to crowded, maybe the button arrow is always visible and on hover of the group entry the button texture becomes visible?

Okay. While you're at it, also consider moving it to the left as that's where it usually is in most programs, e.g. see Windows Explorer:

![image](https://user-images.githubusercontent.com/8611110/189478774-04f6af38-3e95-4701-8203-a62844df468b.png)

**Comment by isXander** [comment]
https://user-images.githubusercontent.com/43245524/189479000-513e01e0-335b-4a01-a4b5-220d5352c822.mp4

**Comment by isXander** [comment]
![image](https://user-images.githubusercontent.com/43245524/189479179-efb0a710-86f1-446a-ba78-fdf0c7d65d1c.png)

**Comment by Madis0** [comment]
That looks good.
