### ISSUE TITLE
crash on 1.20.1fabric with quite a lot mod

### ISSUE THREAD

**Issue by vocaloidkiss** [isXander/YetAnotherConfigLib#165]
[crashreport-2024-4-20_18.21.43.zip](https://github.com/isXander/YetAnotherConfigLib/files/15047823/crashreport-2024-4-20_18.21.43.zip)

**Comment by Bernasss12** [comment]
Any particular reason to report it to this mod in specific?

**Comment by mpustovoi** [comment]
It's some kind of Crowdin-related bug, that happens on Fabric 1.20.1 and 1.20.4 according to people
Personally, I have a crash on Forge 1.20.1

**Comment by isXander** [comment]
Update to 3.4.1
