### ISSUE TITLE
error while loading in 1.20.4 Fabric (v3.4.0)

### ISSUE THREAD

**Issue by nEONcReepER990** [isXander/YetAnotherConfigLib#166]
!! I have installed around 100 other mods. !!
Assuming its your mod because when i install the previous version(v3.3.2) it doesn't happen

Log: 
[latest.log](https://github.com/isXander/YetAnotherConfigLib/files/15081298/latest.log)

Crash report: 
[crash-2024-04-23_20.24.03-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/15081295/crash-2024-04-23_20.24.03-client.txt)

may help
Google Gemini spitted out this from the crash log:
"
Minecraft Crash Analysis
The provided Minecraft crash report indicates an issue with the  CTResourcePack.fromPath function from the mod Crowdin Translate.  Let's break down the crash and potential solutions:

Error:
Exception: ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
Location: de.guntram.mcmod.crowdintranslate.CTResourcePack.fromPath (Line 112)

Cause:
The error suggests the CTResourcePack.fromPath function is trying to access an element at index 1 of an array that only has a length of This means the function is expecting at least two elements but is only finding one.
"

**Comment by nco2k** [comment]
i have a similar problem. when i go back to 3.3.2, everything works fine. will try to gather more info.

**Comment by IJuanTM** [comment]
Same issue on 1.20.1

**Comment by memphismc** [comment]
same issue on fabric 1.20.1

**Comment by memphismc** [comment]
> This is a problem with crowdin translate

is there something that can be done to fix it or do we just keep the outdated mod instead of upgrading??

**Comment by nEONcReepER990** [comment]
@memphismc @IJuanTM @nco2k sorry for tagging but i have found out that the combination with [ChunksFadeIn](https://modrinth.com/mod/chunks-fade-in) crashes, at least in my case 
crash log: 
[crash-2024-04-24_20.16.10-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/15098710/crash-2024-04-24_20.16.10-client.txt)
log: 
[latest.log](https://github.com/isXander/YetAnotherConfigLib/files/15098713/latest.log)

**Comment by mpustovoi** [comment]
Same on Forge 1.20.1

**Comment by Poopooracoocoo** [comment]
https://github.com/gbl/CrowdinTranslate/issues/22

**Comment by isXander** [comment]
Update to 3.4.1
