### ISSUE TITLE
Crash on 1.20.1 fabric

### ISSUE THREAD

**Issue by PiTheGuy** [isXander/YetAnotherConfigLib#167]
Game crashes on startup with an `ArrayIndexOutOfBoundsException`
Crash report: [crash-2024-04-23_20.24.15-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/15084751/crash-2024-04-23_20.24.15-client.txt)

**Comment by ChromaPIE** [comment]
Issue happens after updating YACL to 3.4.0
something related to CrowdinTranslate

**Comment by akaimusic21** [comment]
> Game crashes on startup with an `ArrayIndexOutOfBoundsException` Crash report: [crash-2024-04-23_20.24.15-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/15084751/crash-2024-04-23_20.24.15-client.txt)

Happens on 1.20.4 as well.

**Comment by Fyoncle** [comment]
Happens on also me, crashing :p

**Comment by Poopooracoocoo** [comment]
https://github.com/gbl/CrowdinTranslate/issues/22

**Comment by isXander** [comment]
Update to 3.4.1
