### ISSUE TITLE
3.4.0 crashes with fabric instance 1.20.4

### ISSUE THREAD

**Issue by ryuleik** [isXander/YetAnotherConfigLib#168]
[Render thread/ERROR]: Invalid path : Invalid path ''

crash on Fabric 1.20.4 YetAnotherConfig 3.4.0
launcher: modrinth

crash report on:
https://mclo.gs/l8yYLQJ

**Comment by decheesed** [comment]
Same on 1.20.1, but now it's fixed

**Comment by isXander** [comment]
Update to 3.4.1
