### ISSUE TITLE
Crash while entering config screen on forge

### ISSUE THREAD

**Issue by liangmoe** [isXander/YetAnotherConfigLib#169]
Produce steps: install mods that uses YACL and try to click config button then crash happened
Ive tried [auto hud](https://modrinth.com/mod/autohud) and [Dynamic Crosshair](https://modrinth.com/mod/dynamiccrosshair)
crash report: https://mclo.gs/V8hXQd0

**Comment by mpustovoi** [comment]
Same with [Seamless Loading Screen](https://modrinth.com/mod/seamless-loading-screen) mod.
I guess it happens with all mods that use YACL config system.

**Comment by isXander** [comment]
Looks like the access transformer did not get transfered over. Thanks.

**Comment by trainb0y** [comment]
I'm running into the same issue
NeoForge 20.6.2-beta (1.20.6), YACL 3.4.2+1.20.5

also seems to be the same issue as #132 ?

**Comment by liangmoe** [comment]
Yeah i double checked it, my issue only happened using 3.4.0 and 3.4.1, after update YACL to 3.4.2 then issue just gone, closing, thank you for the hard work💪💪
