### ISSUE TITLE
Crash on startup fabric 1.20.1 

### ISSUE THREAD

**Issue by lowvibes** [isXander/YetAnotherConfigLib#192]
fabric version: `0.15.11`

Minecraft version: `1.20.1`

yacl version: `3.5.0+1.20.1`

Mixin Conflict Helper report:
[mixin.txt](https://github.com/user-attachments/files/16052197/mixin.txt)

Logs:
[latest.log](https://github.com/user-attachments/files/16052208/latest.log)

No crash report generated.

**Comment by Ricci97** [comment]
Its a compatibility problem with the latest "createrailwaysnavigator" mod, 0.5.3 still works fine, something in 0.5.4 is conflicting

**Comment by OrangeSniper** [comment]
agreed

**Comment by lowvibes** [comment]
compatibility problem with Create Railways Navigator fixed as for 0.5.5
