### ISSUE TITLE
Button bug

### ISSUE THREAD

**Issue by ugamii** [isXander/YetAnotherConfigLib#2]
![polymc_ib6PnoQ4GW](https://user-images.githubusercontent.com/111883613/188261644-e9a507a1-9781-40d7-bf07-fcc52dba13f0.gif)
![image](https://user-images.githubusercontent.com/111883613/188261666-17c9b9ed-3881-405d-95be-78f1ce26889d.png)
how to recreate: set interface in minecraft settings to 1 or 2, maximize minecraft window, go to mod config screen

**Comment by isXander** [comment]
Hey! Thanks for taking interest in the project!

This is because Minecraft buttons have a limit of (I think) 400px width so I'm not sure it is possible to correct for, but I'll look into it.

**Comment by isXander** [comment]
Also, I don't know how you actually got a jar as it hasn't been published yet, but you can get it from my snapshot repository with the version of the commit. https://maven.isxander.dev/snapshots
