### ISSUE TITLE
How the fuck do you actually open the GUI?

### ISSUE THREAD

**Issue by X66Herobrine66X** [isXander/YetAnotherConfigLib#202]
I can't believe I need to make this issue, but you didn't actually say how to open the fucking GUI in game. There's nothing on Modrinth. This mod is completely useless to me as I have no idea how to actually use it. Also mods that use this crash the game when you try to open their config with Configured.

**Comment by Imajo24I** [comment]
YACL only provided the screen, it doesn't set it. This means mods themselves have to make the screen accessible.

There are many different ways a mod can make its config screen accessible, most of the time you can access the screen through the configure button in the mod list.

About the crash, what modloader and minecraft version are you using?

**Comment by Emirlol** [comment]
As Imajo24I has said, yacl only provides the screen. To set the current screen to that screen, there are a few methods. Here are 2 that I often use:

For context, `ConfigHandler` is a singleton class that has a method called `generateScreen` to create the config categories/groups/options and then call YACL's `generateScreen` method.

### Command
You can create a command that opens the screen like this on mod initialization:

```kt
ClientCommandRegistrationCallback.EVENT.register { dispatcher, _ ->
	dispatcher.register(
		literal(NAMESPACE)
			.then(literal("config")
				.executes { context ->
					context.source.client.let {
						it.send {
							it.setScreen(ConfigHandler.generateScreen(it.currentScreen))
						}
					}
					Command.SINGLE_SUCCESS
				})
	)
}
```
### Modmenu
Alternatively/additionally, you can add modmenu integration and implement a single interface that usually goes like this:

```kt
class ModMenuApiImpl: ModMenuApi {
    override fun getModConfigScreenFactory() = ConfigScreenFactory(ConfigHandler::generateScreen)
}
```
For modmenu, you'll also have to specify this class you implement as an entry point for `modmenu` key in the FMJ.
