### ISSUE TITLE
1.21.1 compatibility?

### ISSUE THREAD

**Issue by drkhodakarami** [isXander/YetAnotherConfigLib#206]
Hi. The way I understand it, there is no big change between 1.21 and 1.21.1 and most of the mods work without need for rebuilding them. However, when I try to install your mod using atlauncher for 1.21.1, it says that it can't find any compatible version. I think it just needs a little touch on the mod rinth versioning tags maybe?

**Comment by Zalk0** [comment]
Yeah he needs to add 1.21.1 as a supported version

**Comment by Zalk0** [comment]
YACL 3.5.0 Fabric was marked as 1.21.1 compatible on Modrinth!
