### ISSUE TITLE
Add translation keys for the "Close" and "Done" buttons

### ISSUE THREAD

**Issue by Felix14-v2** [isXander/YetAnotherConfigLib#21]
In my language, the word "Cancel" has many meanings, and the one that is currently being used does not match the situation in which the mod uses it.
![2022-09-12_21 59 42](https://user-images.githubusercontent.com/75726196/189735436-a8a43047-84b1-4332-b989-9164a38a858a.png)

The situation is similar with the "Done" (Готово) button: this variant is allowed, but only if you did not need to save changes with a separate button before clicking on it (this is exactly what appears in YACL).
![2022-09-12_22 33 08](https://user-images.githubusercontent.com/75726196/189740081-c08cccc1-1d3d-47a1-b44a-caa9db2d5465.png)

**Comment by Felix14-v2** [comment]
By the way, I contacted the proofreader about the translation of "Done", and he replied that he didn't know why there was such a translation now. Perhaps this will be fixed in the future. But for now, the issue still exists.

**Comment by MattiDragon** [comment]
Minecraft provides translated cancel and done texts in `ScreenTexts`

**Comment by Felix14-v2** [comment]
> Minecraft provides translated cancel and done texts in `ScreenTexts`

I know, but using them is incorrect in this context.

**Comment by isXander** [comment]
then that is a minecraft localisation issue then?

**Comment by Felix14-v2** [comment]
> then that is a minecraft localisation issue then?

No, that is an issue of the word meanings in different situations. The official Minecraft translation is correct in the places it used in vanilla, but in case of your mod, it is more appropriate to use the another translation:
`Cancel –> Назад` (Back) and `Undo –> Отменить`

Both `Cancel` and `Undo` in Russian are `Отменить` (or `Отмена`, just a different form), so here is the issue.
In this situation I can either localize `Cancel` as `Назад`, or replace `undo` with `restore` (`Восстановить`, made in #28 ). The second option is not an ideal solution because we are changing the source meaning to avoid the tautology, but it is all i can do as long as you get the translation for `Cancel` from the Minecraft strings.

**Comment by isXander** [comment]
`yacl.gui.cancel` and `yacl.gui.done` are now available to translate. If not translated, it will use the vanilla one.

**Comment by Felix14-v2** [comment]
Thanks a lot!
