### ISSUE TITLE
Scroll speed is very slow

### ISSUE THREAD

**Issue by intergrav** [isXander/YetAnotherConfigLib#29]
Exactly the title, the scroll speed seems to be very slow in the menu when using the scroll wheel and I am not sure how to fix it.

**Comment by TheKodeToad** [comment]
It's much slower than in vanilla.
![Screencast from 2022-11-10 10-43-12.webm](https://user-images.githubusercontent.com/57493648/201070496-43bd64d7-c5b9-42be-9e10-62f380f31b9b.webm)

**Comment by isXander** [comment]
I believe minecraft's scrolling speed depends on how much there is to scroll. I'll look into bypassing this with a constant scroll speed.

**Comment by TheKodeToad** [comment]
> I believe minecraft's scrolling speed depends on how much there is to scroll. I'll look into bypassing this with a constant scroll speed.

Nope, Minecraft uses a constant scroll speed
