### ISSUE TITLE
Add a bit more padding to the sides of the menu

### ISSUE THREAD

**Issue by intergrav** [isXander/YetAnotherConfigLib#30]
Not sure if this is an issue for YACL or XSO, but maybe add a little bit more padding to the sides of this menu.

Instead of this:

![image](https://user-images.githubusercontent.com/42325132/192639917-df04517c-dba9-4f60-a0d1-9ca7275931a8.png)

It could be like this: (this is done with image editing, so the background is a bit odd but I think you get what I mean)

![image](https://user-images.githubusercontent.com/42325132/192639877-b04d4052-6a4e-40a1-8a3a-e94ed7200df4.png)

This would be great to improve the user experience

**Comment by intergrav** [comment]
I don't see why the menu has to completely span across the screen, the buttons don't need to be that wide. I think it looks better this way tbh, it's more readable to me

**Comment by isXander** [comment]
I don't think there is much point in doing this. Width is very valuable in this gui, removing it for no reason isn't the best idea.
