### ISSUE TITLE
Game can freeze with larger strings saved in config.

### ISSUE THREAD

**Issue by AzureAaron** [isXander/YetAnotherConfigLib#32]
After inputing larger strings into config options, at higher GUI scales (7 for me) attempting to open the config menu will cause the game to freeze and become unresponsive.

Steps to reproduce:
1. Create/have a mod with a string input option in the config
2. Use a lower GUI scale and copy something that's too long to input at higher GUI scales (Hypixel api key for me)
3. Paste the string into the input box and save the changes.
4. Increase your GUI scale to something large (7 in my case)
5. Attempt to open the config menu
❌ Game freezes and becomes unresponsive

**Comment by isXander** [comment]
Unfortunately it's impossible to test this at such high GUI scales as I don't own a monitor that large. If it crashes at all, send the full latest.log, that would help a lot.
