### ISSUE TITLE
"Simple mode" or something that sounds a bit cooler

### ISSUE THREAD

**Issue by TheKodeToad** [isXander/YetAnotherConfigLib#34]
In some mods, there's only one category. It would be nice to hide the sidebar and maybe move the buttons into the centre like with cloth and other libs.

**Comment by isXander** [comment]
I feel like just naming your one category your mod name works fine. Having two different interfaces depending on just adding one more categories wouldn't be very consistent design and may confuse users. I'm up for other suggestions though...

**Comment by TheKodeToad** [comment]
> I feel like just naming your one category your mod name works fine. Having two different interfaces depending on just adding one more categories wouldn't be very consistent design and may confuse users. I'm up for other suggestions though...

Fair point... it may be weird to have two styles for a config lib. Having one category is also quite confusing though. Maybe just an option to hide replace the single category button with more of a label?
