### ISSUE TITLE
Support for non-AWT colours in ColorController

### ISSUE THREAD

**Issue by TheKodeToad** [isXander/YetAnotherConfigLib#35]
It's not that great being forced to use java.awt.Color. Maybe just use ints and accept a java.util.Function to convert back and forth a custom class. When using GSON, it causes some reflection exceptions with AWT colours. I did manage to fix this with an extra class, though.

**Comment by isXander** [comment]
You aren't forced to use java.awt.Color and are free to use whatever you wish. There is a UnaryOperator parameter where you can build on the gson builder to add whatever you wish.

**Comment by TheKodeToad** [comment]
> You aren't forced to use java.awt.Color and are free to use whatever you wish. There is a UnaryOperator parameter where you can build on the gson builder to add whatever you wish.

GSON builder? I'm talking about using ColorController. You'd have to reimplement the whole class using int or another colour class.

**Comment by isXander** [comment]
Oh sorry, I thought you were talking about the config API.

**Comment by isXander** [comment]
After looking into this, it would just be the case of still using java.awt internally to process colours but a different controller implementation to handle that conversion. I think it would just be better if you implemented your own controller that uses `ColorControllerElement` for the actual GUI.

**Comment by mrbuilder1961** [comment]
i know this is closed but i think it would be extremely beneficial to reconsider. the simplest solution could just be letting users specify a transformer that's applied to the get and set calls of the option. 

i understand rewriting the controller is too over the top but, as pointed out earlier, who is using awt colors??? int, `TextColor`, hell even `ChatFormatting` is more widely used. it's just such a pain to make these weird wrappers that are so sensitive and bug-prone, especially between versions.

that being said i discovered this suggestion wayyyy too late for it to be able to benefit me if implemented, so do what you want. but i dont see any world where this would go unused or unappreciated
