### ISSUE TITLE
Server side configuration support

### ISSUE THREAD

**Issue by DanielGolan-mc** [isXander/YetAnotherConfigLib#37]
Hello! I recently noticed this library on Quilt's discord server.

I would like to use it - but for a server side mod. Your readme says,
> - **Client sided library.** YACL is built for client mods only, making it a smaller size.

I would like a lot to use it for my server-side mod. Is it possible? If not, will you add support for it? If not, why?

I just read the documentation, it seems to me like the readme isn't updated? I can't see what's the problem to use it server-side.

P.S. the mod is mandatory on the server, and optional on the client - I plan to use the mod's config loading on the server, and saving on client (obviously, I can't have a screen on server) - is there a problem with that?

**Comment by DanielGolan-mc** [comment]
> I'll leave this issue open as you are right in using Config API for both sides and GUI for client side, so I'll look what I can do to structure the code to separate the two better.

Tnx for noticing! My team is really excited about the mod, and I'm excited about finding a simple config mod.

**Comment by isXander** [comment]
Fixed in d163b91

**Comment by DanielGolan-mc** [comment]
> Fixed in d163b91

May I ask when will this be released?
