### ISSUE TITLE
The tops of string inputs are cropped

### ISSUE THREAD

**Issue by doinkythederp** [isXander/YetAnotherConfigLib#44]
![33231](https://user-images.githubusercontent.com/75394401/206945603-1858ea34-23f4-4f0e-a172-01c8a41094bf.png)

The top pixel of string inputs is cropped off, making letters look inconsistently sized.

**Comment by doinkythederp** [comment]
![74197](https://user-images.githubusercontent.com/75394401/206946585-a8e400f7-e019-4f49-ab39-7d82c97118a5.png)

**Comment by mrbuilder1961** [comment]
I still experience this issue in certain resolutions, including fullscreen. However, for me it affects both the name of the option and the input string. (sorry for the bad image) minecraft 1.19.2, mod version 1.7.1. config options are from an unreleased dev version of my mod [wheresmychathistory](https://github.com/mrbuilder1961/WheresMyChatHistory)

![image](https://user-images.githubusercontent.com/66807297/213933568-46bd1eef-d25b-4a0a-b24c-6459bd4fafa2.png)

**Comment by isXander** [comment]
I believe this is a problem with vanilla text scaling, not YACL scissor as you can see the first and second option cut-off is at a different place.
