### ISSUE TITLE
Config Button Missing

### ISSUE THREAD

**Issue by Obscure2020** [isXander/YetAnotherConfigLib#45]
This morning, I installed v2,1,1 on my 1,19.3 Fabric instance. After playing for a while, I noticed something strange: the Configuration button is now missing from Mod Menu!

For demonstration, here's some screenshots with Cull Less Leaves, which uses Yet Another Config Lib.\
Here's what we got with the previous version of YACL:\
![image](https://user-images.githubusercontent.com/69320464/207704087-6bdd2af8-abe0-45d9-8ecd-04cab1460bf6.png)\
![image](https://user-images.githubusercontent.com/69320464/207704170-ed42ca39-5019-4780-bd42-6108d075bf12.png)

And here's what we get with the latest version of YACL:\
![image](https://user-images.githubusercontent.com/69320464/207704676-051821ad-af07-41ad-ab8b-f604f0ddf769.png)\
![image](https://user-images.githubusercontent.com/69320464/207704777-f50eced4-a298-4561-9faf-6da9641dd90a.png)

As you can see, the configuration button for Cull Less Leaves is now gone. I don't think I need to explain why this is kinda unhelpful.

I have confirmed that the only thing that changed was YACL. Nothing else changed. I also rolled back and re-updated my version of YACL and the results are consistent.

Not sure if this is relevant, but just in case, the version of Mod Menu I'm using is v5.0.2.

**Comment by Obscure2020** [comment]
Did a little more poking around in my mod stack, because I could have sworn I had another mod that uses YACL. Turns out I did: Zoomify! I only just now realized you are also the author of Zoomify. Neato!

Anyway, with v2.1.1 of YACL installed, here's what I'm getting for Zoomify in Mod Menu:\
![image](https://user-images.githubusercontent.com/69320464/207706882-860bf122-de27-4d54-938a-26cc28552c6d.png)

The fact that this bug also seems to be affecting Zoomify suggests to me (although this is still a guess) that YACL is at fault, rather than the mods that (try to) use YACL.

**Comment by Obscure2020** [comment]
The buttons have returned with the latest updates to Cull Less Leaves and Zoomify.

![image](https://user-images.githubusercontent.com/69320464/207979648-f77a4b59-1315-4322-9cb7-798f62d47060.png)

![image](https://user-images.githubusercontent.com/69320464/207979695-2a151876-79ed-4304-8e14-c3306c88a0a2.png)

**Comment by Mark1ed** [comment]
Zoomify 2.9.1 and cull less leaves 1.1.0 are not available for 1.19.2. We need a fix for this! Should I just downgrade the yacl version?
