### ISSUE TITLE
2.1.1 has a breaking change - should be 3.0

### ISSUE THREAD

**Issue by ccrvincent** [isXander/YetAnotherConfigLib#46]
I saw you mention on Discord that 2.1.1 is a breaking change that requires downstream changes.

This should be retracted and re-released as 3.0 so anyone who is using wildcards aren't caught by surprise.

**Comment by isXander** [comment]
Bit late for that unfortunately...

**Comment by ccrvincent** [comment]
Never too late to fix a semver mistake.

Too late to fix it and not break things, maybe.  ;)
