### ISSUE TITLE
Values visually reset to original values after saving.

### ISSUE THREAD

**Issue by Giggitybyte** [isXander/YetAnotherConfigLib#48]
Setting a value then saving it will cause all values to revert to their original state when the screen was first opened.
Closing then reopening the screen will read the updated value.

https://user-images.githubusercontent.com/19187704/208584816-dbf99a98-10a0-4767-b48a-98c5c2bcc4db.mp4

MC 1.19.3
YACL 2.1.1

**Comment by isXander** [comment]
You have most likely implemented the binding wrong. YACL explicitly resets the pending value upon applying options. Could you send your binding code?

**Comment by Giggitybyte** [comment]
My full implementation is here: https://github.com/Giggitybyte/SleepWarp/blob/retrofit/src/main/java/me/thegiggitybyte/sleepwarp/SleepWarp.java#L39-L92

**Comment by isXander** [comment]
Have you considered using YACL's config API rather than your own? It may fix your issues.

**Comment by Giggitybyte** [comment]
Wasn't aware of it, but I want to stick with what I made. 
I don't understand how that'd affect anything anyways; the source of the config value should not cause issues like this.

**Comment by isXander** [comment]
When you click 'Apply Value', two things happen:
1. The values stored in the options are passed to your binding setter
2. The stored value in the options is set to the binding getter

The problem lies in step number 2. Your config doesn't seem to update instantly and the binding getter is still the old value.

**Comment by Giggitybyte** [comment]
My config does update instantly as you can see in my video above; YACL calls the method which saves my config and writes the updated values. The UI simply resets to the previous value.

**Comment by Giggitybyte** [comment]
Any update on this issue?

**Comment by Giggitybyte** [comment]
Frustrated over this issue I decided to debug this further and understand why the binding was always returning the old value when I clearly see it set the new value, and I couldn't for the life of me figure out where the hell it was getting that value from. On a whim, I decided to swap out the method reference that I've been providing for each binding getter with a lambda; it now works exactly as intended.

My question is: why? That was the only thing I changed in the whole setup. Why does this make a difference?

**Comment by isXander** [comment]
No idea.

**Comment by Giggitybyte** [comment]
Might want to add a note in the documentation about this.

**Comment by isXander** [comment]
I added a warning log to let developers know *something* is going wrong in the aforementioned step 2.
