### ISSUE TITLE
Support for Lists of custom objects in GUI builder

### ISSUE THREAD

**Issue by TechPro424** [isXander/YetAnotherConfigLib#54]
Currently, there does not seem to be a way to build GUIs for configs with Lists of custom objects, please add a way to do this

For example, if I have a custom class such as 
```java
public class CustomObject {
  String a = "abcd"
  ArrayList<String> b = new ArrayList<String>()
}
```

And the following config entry 
```java
@ConfigEntry public ArrayList<CustomObject> customObjects = new ArrayList<CustomObject>();
```

There does not seem to be a way to build a GUI for it. Please add a way to do so.

**Comment by isXander** [comment]
use the `CyclingListController`

**Comment by TechPro424** [comment]
@isXander I don't really understand how it works, could you please explain?

**Comment by Jack-Works** [comment]
@isXander No, `CyclingListController` is used to "where once clicked, cycles through in the provided list." (in the JavaDoc). I think it is used to cycle through something like an enum, not for custom objects.

<img width="849" alt="image" src="https://github.com/isXander/YetAnotherConfigLib/assets/5390719/1e393935-b3ae-4b02-9e4d-5e0c20d0ef27">

I wrote my own Controller and Widget to render this GUI, but it cannot save the config in the custom object. I wonder is there an example of this?
