### ISSUE TITLE
Support for Listeners on ListOptions

### ISSUE THREAD

**Issue by Crendgrim** [isXander/YetAnotherConfigLib#55]
Regular options can register a listener that triggers on value change. It would be great to have this option also for ListOptions, both to see when the list itself changes, and when the inner controller changes a value in the list. Personally, I mostly need the second.

**Comment by Crendgrim** [comment]
Ah, I figured out that I can manually add a listener to the ListOption object after it was constructed. So the actual feature request would be to expose this in the Builder already.

**Comment by isXander** [comment]
Yeah seems like I missed this on the builder.
