### ISSUE TITLE
Adaptive tooltips don't see latest version of YACL

### ISSUE THREAD

**Issue by variety754** [isXander/YetAnotherConfigLib#62]
<img width="584" alt="Screenshot 2023-04-26 184759" src="https://user-images.githubusercontent.com/124847943/234522401-a32e9b63-a96f-471e-ad48-0ee37d37f155.png">
I get this issue on latest version of both mods on 1.19.3
<img width="718" alt="Screenshot 2023-04-26 184822" src="https://user-images.githubusercontent.com/124847943/234522654-57582827-987b-44b6-85ae-67ff48ad86c4.png">

**Comment by variety754** [comment]
I think I know what's  the problem. Its forge version of this modification, but you by accident gave it Fabric tag and it was automatically updated on this version in my modpack

**Comment by electricgamez** [comment]
Looks like they accidently flipped the forge and fabric version as I had the same problem but I had the Forge version instead of the fabric version I need

**Comment by isXander** [comment]
I fixed it now

**Comment by variety754** [comment]
Its still updates me to 2.5.0 forge version when I'm in fabric modpack
