### ISSUE TITLE
Latest Forge Version is also shown within CurseForge fabric profil

### ISSUE THREAD

**Issue by Cape-City** [isXander/YetAnotherConfigLib#63]
![grafik](https://user-images.githubusercontent.com/122229367/236632819-71a9f5c0-9586-4ec9-87b8-5941cee2230b.png)

...and wants to update it, but then the mod will be ignored of course while loading into MC.

**Comment by Cape-City** [comment]
![grafik](https://user-images.githubusercontent.com/122229367/236637266-3f34360c-c9d8-420c-9b49-38f65a63e9b3.png)

The fabric version crashes MC during startup

**Comment by Shadowpudding** [comment]
It is also happening with the 1.20 files and some files are showing up duplicated
![Screenshot 2023-06-10 212210](https://github.com/isXander/YetAnotherConfigLib/assets/60038503/b02320ef-b479-46d3-b1d8-05d55f2952b7)

**Comment by isXander** [comment]
I can't do anything about this. This is the fault of curseforge. I recommend modrinth
