### ISSUE TITLE
Current category button does not appear as "selected"

### ISSUE THREAD

**Issue by Qendolin** [isXander/YetAnotherConfigLib#66]
## What should happen?
When selecting a category the button should appear as selected (have a white outline).

## What actually happens
The category buttons work like any other button, making it hard to tell wich category is currently selected.

## Solution
I think the problem is this function:
https://github.com/isXander/YetAnotherConfigLib/blob/5b368af9efcc1c587c608d014e9dc79bcc3c691c/common/src/main/java/dev/isxander/yacl/gui/CategoryWidget.java#L21-L31
It doesn't get called, (or I just couldn't get the debugger to stop there). This is probably because `getTextureY` is declared as `private` in `PressableWidget` (yarn mappings). This might have changed in a recent Minecraft version.

## Environment
Minecraft Fabric 1.19.4
YACL 2.5.1+1.19.4

**Comment by isXander** [comment]
Thank you for taking the time to debug this. YACL 3.x will no longer have this problem. So I'll close as won't fix.
