### ISSUE TITLE
Option menu for mods that depend on YACL fails to load

### ISSUE THREAD

**Issue by RealmKebab** [isXander/YetAnotherConfigLib#70]
![image](https://github.com/isXander/YetAnotherConfigLib/assets/73048123/f2d11239-a4ca-435b-a9bf-98b040edf81a)
**This is a problem with YACL, I tried it with zoomify and it failed too.**

**Comment by isXander** [comment]
Because you are trying to use YACL 3.0 when these mods use YACL 2.0. It is a breaking update.
