### ISSUE TITLE
Crash with YACL 3.0.1 and Some Mods

### ISSUE THREAD

**Issue by jetblackrx89** [isXander/YetAnotherConfigLib#78]
I found that for some reason, this combination of mods causes a crash on 1.19.4:

- Blur 3.0.0
- Dynamic Crosshair 6.2.1 (optional YACL dependency)
- YACL 3.0.1

When clicking any menu button from the main screen, the attached crash is observed. What's weird is removing Blur fixes it, but so does having Blur *and* a mod called "First-person (Fabric)" installed in combination seems to for some reason avoid it.

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector modifyChildrenCall(Lnet/minecraft/class_350;)Ljava/util/List; in #yet_another_config_lib:yacl.mixins.json:AbstractSelectionListMixin from mod yet_another_config_lib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap yet-another-config-lib-common-refmap.json`

[crash-2023-06-11_22.10.30-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/11716906/crash-2023-06-11_22.10.30-client.txt)

**Comment by bop34** [comment]
Also experiencing this, although I am not certain whether or not yacl is actually causing the issue.

**Comment by Officialy** [comment]
Yeah can confirm I'm getting this too. Same way to crash too, any UI button = crash.

**Comment by pPingu7** [comment]
Yes, I also had this problem, where the game crash after pressing any button in the starting menu, with any version above 3.0 and when I just changed YACL to version 2.5 it didn't crash anymore. In the log was something about the essential mod which I have intalled, so maybe this one is also incompatible...

**Comment by isXander** [comment]
3.0.3 fixed this
