### ISSUE TITLE
YACL and certain mods on Quilt cause crash when any button is clicked

### ISSUE THREAD

**Issue by ParodyVerse** [isXander/YetAnotherConfigLib#84]
The mods work just fine without YACL
Minecraft 1.19.4
Quilt 0.19.1
YACL 3.0.3
HT's Treechop 0.17.9
Coordinates Display 2.3.2 and 2.2.0
PicoHUD 1.4.0
[crash-2023-06-25_17.09.41-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/11872427/crash-2023-06-25_17.09.41-client.txt)
[crash-2023-06-25_17.48.36-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/11872428/crash-2023-06-25_17.48.36-client.txt)
[crash-2023-06-25_18.02.23-client.txt](https://github.com/isXander/YetAnotherConfigLib/files/11872429/crash-2023-06-25_18.02.23-client.txt)

**Comment by SyberiaK** [comment]
Can confirm for Fabric 1.20.1, YACL 3.1.0

**Comment by SyberiaK** [comment]
I managed to fix it by simply creating new instance in Prism.

**Comment by isXander** [comment]
A YACL update fixed this recently.
