### ISSUE TITLE
yet-another-config-lib-forge-3.0.3+1.20.jar is marked as Fabric-compatible on CurseForge

### ISSUE THREAD

**Issue by Avakining** [isXander/YetAnotherConfigLib#86]
As in title, `yet-another-config-lib-forge-3.0.3+1.20.jar` is marked as being compatible with Fabric on Curseforge, leading it to be shown as an available update.

**Comment by suerion** [comment]
The issue is here with 3.1.0 please update the compatiblity.

Fabric Loader loads allways the Forge version
