### ISSUE TITLE
Images in descriptions crash when looked at, plus weird effect on .webps

### ISSUE THREAD

**Issue by mrbuilder1961** [isXander/YetAnotherConfigLib#87]
### info
version info: mc 1.19.4, yacl 3.0.4+1.19.4, loader 0.14.21, api 0.85.0+1.19.4, modmenu 6.2.3
windows 10, nvidia rtx 3060, i9-119000k
chat patches 194.5.1 (dev/debug build)
- ***[all libs w the source of the debug lib used when these bugs occurred, if you need anything specific just lmk: [all_libs.zip](https://github.com/isXander/YetAnotherConfigLib/files/12009976/all_libs.zip)]***

(sorry if i forgot anything, im not super good memory w specific things)

### desc
so in dev, the (.webp !!) images load and work fine, although they do have a weird distortion/artifact/effect thing going on with all of them, but a couple aren't really noticable. i checked in paint.net and they look fine, so it must be some weird rendering/GLFW/hardware issue, but that's as far as i would know. **note: this did NOT happen with .jpeg images, so maybe it has to do w the compression or something, i remember seeing something in the discord about that being a problem earlier. idk tho, you're the expert.**

however, the main issue is that in prod, even with only required mods for chat patches (fabric loader+api, modmenu, and yacl) it still crashes when hovering over any button w an image. this error also happened with .jpeg images, but i switched back to .webp s (because of [this](https://github.com/isXander/YetAnotherConfigLib/compare/3.0.3+1.19.4...3.0.4+1.19.4)) and it persisted.
here are some images, a video to show the effect better, and a log from both using jpg and webp. note that both logs have way more mods, not only the requirements, so there could also be incompatibilies.

### media and logs
** [jpeg log](https://mclo.gs/hCBFZ7W) and [webp log](https://mclo.gs/Hb5DSz1) (ignore the webp link saying they're jpg files, i forgot to change the log message) **

***clearly see the effect: https://github-production-user-asset-6210df.s3.amazonaws.com/66807297/252530488-ae656348-68de-4e52-b466-b3cd06dc53fe.mp4***

weird shift chat: 
![image](https://github.com/isXander/YetAnotherConfigLib/assets/66807297/e0be83f4-196c-4d7e-9083-cf68ee7d2de2)
vs actual shift chat
![image](https://github.com/isXander/YetAnotherConfigLib/assets/66807297/9004b4be-34e3-44ef-901c-1d6200ef3246)

weird chat drafting 
![image](https://github.com/isXander/YetAnotherConfigLib/assets/66807297/b978e9d3-ae1a-4515-a0f2-e5c74ff937a2)
vs actual chat drafting:
![image](https://github.com/isXander/YetAnotherConfigLib/assets/66807297/103b121e-b60d-4346-b244-21ee8d450e25)

**Comment by mrbuilder1961** [comment]
any updates w this?

**Comment by isXander** [comment]
I don't really see any issue? All I can see is WebP compression.

**Comment by mrbuilder1961** [comment]
like you cant reproduce it? i literally cannot use images because they crash the game

**Comment by mrbuilder1961** [comment]
ok i think i fixed it on my own, probably had to do with [this hacky resource stream getter thing](https://github.com/mrbuilder1961/ChatPatches/blob/25ad12ade53fbac110974fae7943e4adb5f1bedd/src/client/java/obro1961/chatpatches/config/YACLConfig.java#L266). it would have been a lot more convenient if i knew that you could just get the `Resource` from the `Identifier` and then get a stream there lol. anyways, maybe just put a warning somewhere not to use the `ClassLoader` route. other than this final thing below, the issue seems to have already been fixed, so thanks !

the only other thing is the logs get spammed with this message, although everything seems to load fine:
```log
[00:06:12] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid texture format.'
```
![image](https://github.com/isXander/YetAnotherConfigLib/assets/66807297/e57c06aa-88a1-40cb-9caa-545894485b79)

**Comment by isXander** [comment]
> ok i think i fixed it on my own, probably had to do with [this hacky resource stream getter thing](https://github.com/mrbuilder1961/ChatPatches/blob/25ad12ade53fbac110974fae7943e4adb5f1bedd/src/client/java/obro1961/chatpatches/config/YACLConfig.java#L266). 

That is definitely not how you're supposed to load images. You pass your `Identifier` to `OptionDescription.Builder#webpImage`! That's it!

I am aware of the OpenGL error but not sure how to fix it, but is a non issue!
