### ISSUE TITLE
curseforge issue affecting yetanother

### ISSUE THREAD

**Issue by GlimmerfallDev** [isXander/YetAnotherConfigLib#91]
the latest release of forge version seems to be tagged as fabric, because that's what curseforge is tagging it as, thus, my mods didn't work on my fabric modpack until I figured out what was going on and manually installed the correct version.  just letting you know.

**Comment by suerion** [comment]
its the same issue as this one ->
https://github.com/isXander/YetAnotherConfigLib/issues/86
