### ISSUE TITLE
GL error when loading WebP + GIF images

### ISSUE THREAD

**Issue by Phoenix-Starlight** [isXander/YetAnotherConfigLib#96]
I've repeatedly gotten segfaults, and then after dropping No Error Context option gotten this:
`[14:55:28] [Render thread/INFO]: OpenGL debug message: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glTexSubImage2D(invalid texture level 0)'`
Eventually I isolated it to just YACL/Zoomify causing the issue. (Also, after this error occurs, the revert icons are broken)
[issue.log](https://github.com/isXander/YetAnotherConfigLib/files/12270729/issue.log)
If I've misplaced the issue, please let me know!

**Comment by isXander** [comment]
This is not casusing a segfault. I am aware that loading WebP and GIF images cause this error log, but they load find and is not causing any issues.

**Comment by isXander** [comment]
I've renamed this issue and am using this as a tracking issue for this problem.

**Comment by Phoenix-Starlight** [comment]
It's segfaulting beacuse I enabled no error context in sodium which is
why it chose. If you turn off no error context then it doesn't.
